# Generated by Django 4.1.7 on 2023-03-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(
                default="Default description...update me please...",
                verbose_name="Description",
            ),
        ),
    ]
