# Generated by Django 4.1.7 on 2023-03-07 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="agent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_review",
                to="profiles.profile",
                verbose_name="Agent being rated",
            ),
        ),
    ]
